language: python

python:
- 3.8

install: 
  - pip install -r $PWD/mysite/requirements.txt

script:
  - black --check . || true
  - flake8
  - coverage run --source= $PWD/mysite/manage.py test
  
after script:
  - coveralls
