language: python

install: 
  - pip install -r $PWD/mysite/requirements.txt
  - python -m pip install flake8


script:
  - black --check . || true
  - flake8
  - coverage run --source= $PWD/mysite/manage.py test
  - coverall
